version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: Bilel1998
      MONGO_INITDB_ROOT_PASSWORD: Bilel1998
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
